export default {
  products: [
    {
      _id: "1",
      name: "Hiskywin Full Zip Running Shirts Thermal Workout",
      category: "shirts",
      image: "/images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt",
      category: "Jumper",
      image: "/images/product-2.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.5,
      numReviews: 13,
      countInStock: 5,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Hoodie",
      image: "/images/product-3.jpg",
      price: 40,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sport style Tricot Joggers",
      category: "pants",
      image: "/images/product-4.jpg",
      price: 60,
      brand: "Under Armour",
      rating: 4,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Skechers Men's Skech-Sweats Diamond Logo Jogger Sweatpant",
      category: "pants",
      image: "/images/product-5.jpg",
      price: 60,
      brand: "Skechers",
      rating: 3.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "'Warning Tunnel' Black Streetwear Pants",
      category: "shirts",
      image: "/images/product-6.jpg",
      price: 59.95,
      brand: "Kaitama",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
